require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'PNM_179_Test_Project' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-branch', path: '../node_modules/react-native-branch'
  # pod "Branch-SDK", path: "../node_modules/react-native-branch/ios"
  pod 'Branch'

  target 'PNM_179_Test_ProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'PNM_179_Test_Project-tvOS' do
  # Pods for PNM_179_Test_Project-tvOS

  target 'PNM_179_Test_Project-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
